### ISSUE TITLE
[BUG]: Upload service CORS issue

### ISSUE THREAD

**Issue by Ruitjes** [Ruitjes/blind-date#98]
Wasn't this issue already solved? 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/26769441/173022830-3cb04862-4873-4952-ab36-382fff8a7ab5.png">

**Comment by kevinbevers** [comment]
Fixed, there where miss configurations in the kubernetes file. Secrets where wrongly configured so the access key and bucket name where ""
